language: "node_js"
node_js:
    - "node"
services:
  - mongodb
install:
  - npm install -g serverless
  - npm install
script:
  - npm test
deploy:
  skip_cleanup: true
  provider: script
  script: sls deploy
  on:
    branch: master